apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nginx-server
  labels:
    app: nginx-server
  name: nginx-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
      - image: nginx
        name: nginx
