apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-server
  name: nginx-server
  namespace: nginx-server
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-server
